# Generated by Django 3.2.17 on 2023-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20230311_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
